name: smart_attendance
description: A new Flutter application.


version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  flutter_bloc: ^4.0.0
  equatable: ^1.0.0
  meta: ^1.1.6
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  shared_preferences: ^0.5.7+3
  flutter_launcher_icons: ^0.7.5
  qrcode: ^1.0.4
  barcode_scan: ^3.0.0
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.1
  geocoder: ^0.2.1
  connectivity: ^0.4.8+6
  geolocator: ^5.3.2+2
  url_launcher: ^5.4.11
  flutter_share: ^1.0.2+1

  pdf: ^1.8.1
  printing: ^3.5.0
  path_provider: ^1.6.11
  flutter_share_file: ^1.1.4+1
  #open_file: ^3.0.1

  qr_flutter: ^3.2.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/about/